### ISSUE TITLE
Problema na movimentação do humano.

### ISSUE THREAD

**Issue by eilins** [eilins/Robots.c#1]
Flavio, na chamada da função para movimento do humano, só as condições de ele ir para cima ou para esquerda estão funcionando, quando seleciona outro comando, como por exemplo, ir para esquerda ele some do tabuleiro.

**Comment by flavioduart** [comment]
Vinícius, eu observei isso hoje de madrugada, dei uma ajeitada na condição de movimento do humano, e consegui ajeitar, agora ele anda sem bugs. Só temos que delimitar até onde ele pode andar, mas isso é relacionado a outra issue. Bug corrigido.
