### ISSUE TITLE
Movimentação do Robo

### ISSUE THREAD

**Issue by flavioduart** [eilins/Robots.c#2]
A função que faz o robô andar não está respondendo. Acho que ajeitando os ifs, e talvez mudando as variáveis que guarda a sua nova posição dará resultado.

**Comment by eilins** [comment]
Também tava pensando nisso, mas nesse caso, as variáveis que seriam usada seriam as que guardam a posição do humano, que no caso faria o robô segui-lo. Certo?

**Comment by flavioduart** [comment]
Também estou em duvida em relação a isso, mas acho que não. Acho que seria na própria variável da localização do robô. Por exemplo: Se o humanos estiver uma linha e uma coluna a menos que o robô, ele irá pra tal posição, e essa nova posição será guardada na variável do robô, fazendo ele andar.

**Comment by eilins** [comment]
É, tem lógica isso, vamos testar para vê se funciona. No caso a gente usa P.robos[][], ja que a gente usou A.posição[][] para guardar a posição do humano. Beleza?

**Comment by flavioduart** [comment]
Tudo bem, vamos testar.

**Comment by flavioduart** [comment]
Movimentação de robô feita!
