### ISSUE TITLE
Limite de movimento.

### ISSUE THREAD

**Issue by flavioduart** [eilins/Robots.c#3]
Quando o humano chega no limite do tabuleiro, por exemplo, no canto direito, e o usuário ainda aperta para ele ir pra direita, ele some, em vez de fica parado. Vinícius, será que criando um for ou ifs ajudaria?

**Comment by eilins** [comment]
Creio que utilizando if a gente conseguiria resolver isso. Quando a posição do humano fosse igual  a posição limite do tabuleiro, mostrar uma mensagem de erro: comando invalido. Ai, o usuário ficaria ciente de que chegou ao limite do tabuleiro e iria andar em outra direção.

**Comment by flavioduart** [comment]
Deu certo, isso mesmo. Corrigido.
